version: "3.1"
services:
  # Configures the mysql service
#  Use the latest mysql version
  db:
    image: mysql:latest
    container_name: database
    # let the container restart automatically unless it has been manualy stoped
    restart: unless-stopped
    # Maps the hosts port 3361 to the exposed port 3306 in the mysql container
    ports:
      - 3362:3306
    # set environment variables for the service
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # Attach container to app (network)
    networks:
      - applicationnetwork


  app:
    build:
      # arguments to for user
      args:
        user: mukotso
        uid: 1000
      context: ./
      # Get the Dockerfile to use for image creation from the current directory
      dockerfile: Dockerfile
    image: app
    depends_on:
      - db
    container_name: app
    restart: unless-stopped
    working_dir: /app
    # Map the current directory to the /app directory in the container
    volumes:
      - ./:/app
    networks:
      - applicationnetwork


# configure Adminer - database administration tool for MySQL, PostgreSQL, and SQLite databases
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    depends_on:
      - app
      - db
    networks:
      - applicationnetwork


  # Configures the nginx web server container
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    depends_on:
      - db
      - app
    ports:
      - 8922:80
    volumes:
      - ./:/app
      # Gets the nginx server configuration from the project into the container config (inside docker /nginx folder )
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - applicationnetwork


# Create the network to be used by the containers
networks:
  applicationnetwork:
    driver: bridge
